### ISSUE TITLE
Unify the API of Nim[draft]

### ISSUE THREAD

**Issue by ringabout** [timotheecour/Nim#699]
# Background
As Nim language becomes more mature, some APIs need to be redesigned. some legacy modules has many error-prone APIs and are hard to use. We need an API specification。

## Motivate example

```nim
proc runeSubStr*(s: string, pos: int, len: int = int.high): string =
  ## Returns the UTF-8 substring starting at code point ``pos``
  ## with ``len`` code points.
  ##
  ## If ``pos`` or ``len`` is negative they count from
  ## the end of the string. If ``len`` is not given it means the longest
  ## possible string.
```
In unicode module, `runeSubStr` is very buggy. `pos` can be negative, `len` can be negative. That's a terrible API and brings many confusions. We can rely on `^` to get the right result or only allow natural position.

see https://github.com/nim-lang/Nim/issues/17768

Not finished .......

**Comment by timotheecour** [comment]
> pos can be negative, len can be negative. That's a terrible API and brings many confusions.

agreed, and it hides bugs (note that python has similar behavior, it's a poor-man's way around missing D's `opDollar`, see RFC in https://github.com/timotheecour/Nim/issues/73)

"Unify the API of Nim" is a bit broad and not very actionable (more generally we need a sets of do's and dont's along with rationale, expanding on the guidelines in contributing.rst + nep1.rst, that gets updated with latest features of the language).

But let's refocus this issue on just dealing with APIs involving a container + indexes pointing inside it.

it's not that simple though, what do you suggest concretely, that works with c, js, vm?

IMO this is impossible (in the general case of mutable openArray's) until we fix https://github.com/nim-lang/Nim/issues/15952#issuecomment-786312417 (but that issue is very fixable and very worth fixing)

**Comment by ringabout** [comment]
> let's refocus this issue on just dealing with APIs involving a container + indexes pointing inside it.

I agree

**Comment by ringabout** [comment]
> agreed, and it hides bugs (note that python has similar behavior, 

even worse, they introduce many bugs which are hard to fix if you look at the implementation.

**Comment by timotheecour** [comment]
for this specific example how about:
```nim
proc runeSlice*(s: openArray[char], maxCodePoints = int.high, fromLeft = true): Slice[int]
```
(and then user can reuse `strbasics.setSlice` to get a string if they want)

**Comment by ringabout** [comment]
not fit
